AWSTemplateFormatVersion: "2010-09-09"
Description: Service Catalog Resources

Parameters:
  CloudFormationBucket:
    Type: String

Resources:
  Portfolio:
    Type: "AWS::ServiceCatalog::Portfolio"
    Properties:
      ProviderName: TDA
      DisplayName: Main Portfolio

  S3BucketProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: TDA
      Description: S3 Bucket
      Name: s3-bucket
      ProvisioningArtifactParameters:
        - Description: Just a simple S3 bucket
          Info:
            LoadTemplateFromURL: !Sub https://${CloudFormationBucket}.s3.amazonaws.com/service-catalog/s3-bucket-v10.yml
          Name: v1.0

  S3BucketPortfolioProductAssociation:
    Type: "AWS::ServiceCatalog::PortfolioProductAssociation"
    Properties:
      AcceptLanguage: en
      PortfolioId: !Ref Portfolio
      ProductId: !Ref S3BucketProduct

  PortfolioPrincipalAssociation:
    Type: "AWS::ServiceCatalog::PortfolioPrincipalAssociation"
    Properties:
      PrincipalARN: arn:aws:iam::199603965279:group/Admins
      PortfolioId: !Ref Portfolio
      PrincipalType: IAM

  TagOptionForDepartment:
    Type: AWS::ServiceCatalog::TagOption
    Properties:
      Active: true
      Value: IT
      Key: Department

  AssociationForTagOptionForDepartment:
    Type: AWS::ServiceCatalog::TagOptionAssociation
    Properties:
      TagOptionId: !Ref TagOptionForDepartment
      ResourceId: !Ref Portfolio
