version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gv3l4qc208tp"
s3_prefix = "samapp"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
