AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Function and API for translating

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  QueueName:
    Type: String
    Default: SAMAppQueue
    Description: SQS Queue name
  TableName:
    Type: String
    Default: Texts
    Description: DynamoDB Table Name

Resources:
  TranslateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: translate/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref DynamoDBTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MySqsQueue.QueueName
      Environment:
        Variables:
          TEXTS_TABLE: !Ref DynamoDBTable
          SQS_QUEUE_URL: !Ref MySqsQueue
      Events:
        Translate:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /translate
            Method: post
#            RestApiId:
#              Ref: TranslateApi

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1 
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        AttributeName: expired_at
        Enabled: true
      TableName: !Ref 'TableName'
#      StreamSpecification:
#        StreamViewType: NEW_IMAGE


  MySqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref 'QueueName'


  




Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TranslateApi:
    Description: "API Gateway endpoint URL for Prod stage for Translate function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/translate/"
  TranslateFunction:
    Description: "Translate Lambda Function ARN"
    Value: !GetAtt TranslateFunction.Arn
  TranslateFunctionIamRole:
    Description: "Implicit IAM Role created for Translate function"
    Value: !GetAtt TranslateFunctionRole.Arn
  DynamoDBTable:
    Description: "DynamoDB Table"
    Value: !GetAtt DynamoDBTable.Arn
  SQSQueueURL:
    Description: SQS Queue URL
    Value: !Ref MySqsQueue
